version: '3.7'

services:
  movie_service:
    build: ./movie-service
    image: "${DOCKER_ID}/movie_service:${DOCKER_TAG}"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - movie_db

  cast_service:
    build: ./cast-service
    image: "${DOCKER_ID}/cast_service:${DOCKER_TAG}"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://cast_db_username:cast_db_password@cast_db/cast_db_dev
    depends_on:
      - cast_db

  movie_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_movie:/var/lib/postgresql/data/

  cast_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_cast:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - movie_service
      - cast_service

volumes:
  postgres_data_movie:
  postgres_data_cast: