apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cast.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.cast.service.port }}
      targetPort: {{ .Values.cast.service.targetPort }}
      nodePort: {{ .Values.cast.service.nodePort | default "" }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "fastapiapp.fullname" . }}-cast
